# Error Handling

In [1]:
a

NameError: name 'a' is not defined

In [ ]:
1/0

In [ ]:
1 + 'a'

In [ ]:
if True print('a')

In [ ]:
# Syntax

try:
    pass
except:
    pass
    

In [ ]:
try:
    print(1/0)
except ZeroDivisionError:
    print(f"can't divide by zero")

In [ ]:
try:
    print(1/0)
except ZeroDivisionError as error:
    print(f"can't divide by zero due this --> {error}")

In [ ]:
import ana

In [ ]:
try:
    import ana
except:
    print("Okay")
    

In [2]:
import unittest

In [3]:
def add(x, y):
    return x+y

In [4]:
class TestAdd(unittest.TestCase):

    def test_add(self):
        self.assertEqual(add(4, 5), 9)
        self.assertEqual(add(3, 3), 6)


In [5]:
a = TestAdd()

In [6]:
a

<__main__.TestAdd testMethod=runTest>

In [7]:
a.test_add()

## Pandas and numpy

In [8]:
import numpy as np

In [9]:
a = [2, 4, 6]

In [10]:
[i*2 for i in a]

[4, 8, 12]

In [11]:
a*2

[2, 4, 6, 2, 4, 6]

In [12]:
%%time
l = [i*2 for i in range(1, 1000000)]

Wall time: 221 ms


In [13]:
arr = list(range(1, 1000000))

In [14]:
np_array = np.array(arr)

In [15]:
np_array

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [16]:
ar = np.arange(1, 1000000)

In [17]:
ar

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [18]:
ar

array([     1,      2,      3, ..., 999997, 999998, 999999])

In [19]:
%%time
ar*2

Wall time: 3.93 ms


array([      2,       4,       6, ..., 1999994, 1999996, 1999998])

In [20]:
max([1, 2, 4])

4

In [21]:
max(ar)

999999

In [22]:
a = [2, 3, 44, 5]

In [23]:
arr = np.array(a)

In [24]:
arr.mean()

13.5

In [25]:
arr.max()

44

In [26]:
arr.argmax()

2

In [27]:
arr.argmin()

0

In [28]:
np.median(arr)

4.0

In [29]:
a = np.random.rand(1, 100)

In [30]:
a.ndim

2

In [31]:
a

array([[0.71793214, 0.67563594, 0.52253967, 0.04167261, 0.14699721,
        0.69638648, 0.06752909, 0.26038363, 0.57849085, 0.23064524,
        0.97885657, 0.98194565, 0.37398949, 0.66989927, 0.81590095,
        0.09844093, 0.5256729 , 0.61868235, 0.62748483, 0.82804272,
        0.53332608, 0.33764734, 0.67016465, 0.99960191, 0.04247274,
        0.89133942, 0.56063125, 0.48563517, 0.46811779, 0.16947285,
        0.01679332, 0.80121576, 0.60019687, 0.4180871 , 0.54139131,
        0.16385464, 0.71427997, 0.7468725 , 0.03979845, 0.31187846,
        0.67018195, 0.0523463 , 0.39039137, 0.71881943, 0.9419738 ,
        0.76069868, 0.41317271, 0.36553544, 0.1129596 , 0.46721379,
        0.27196458, 0.65018536, 0.50628528, 0.76961296, 0.55939805,
        0.67033831, 0.39226183, 0.79610719, 0.18793106, 0.1952469 ,
        0.09677996, 0.66499166, 0.06513356, 0.94033067, 0.72741453,
        0.58295232, 0.97025724, 0.51428297, 0.81980038, 0.42192274,
        0.24939717, 0.90090088, 0.72804017, 0.15

In [32]:
a[0].ndim

1

In [33]:
a.flatten()

array([0.71793214, 0.67563594, 0.52253967, 0.04167261, 0.14699721,
       0.69638648, 0.06752909, 0.26038363, 0.57849085, 0.23064524,
       0.97885657, 0.98194565, 0.37398949, 0.66989927, 0.81590095,
       0.09844093, 0.5256729 , 0.61868235, 0.62748483, 0.82804272,
       0.53332608, 0.33764734, 0.67016465, 0.99960191, 0.04247274,
       0.89133942, 0.56063125, 0.48563517, 0.46811779, 0.16947285,
       0.01679332, 0.80121576, 0.60019687, 0.4180871 , 0.54139131,
       0.16385464, 0.71427997, 0.7468725 , 0.03979845, 0.31187846,
       0.67018195, 0.0523463 , 0.39039137, 0.71881943, 0.9419738 ,
       0.76069868, 0.41317271, 0.36553544, 0.1129596 , 0.46721379,
       0.27196458, 0.65018536, 0.50628528, 0.76961296, 0.55939805,
       0.67033831, 0.39226183, 0.79610719, 0.18793106, 0.1952469 ,
       0.09677996, 0.66499166, 0.06513356, 0.94033067, 0.72741453,
       0.58295232, 0.97025724, 0.51428297, 0.81980038, 0.42192274,
       0.24939717, 0.90090088, 0.72804017, 0.15024238, 0.47536

In [34]:
l = np.random.randint(3, 6, size=(3, 3))

In [35]:
l

array([[5, 5, 4],
       [4, 3, 3],
       [5, 4, 3]])

In [36]:
l.ndim

2

In [37]:
l.flatten()

array([5, 5, 4, 4, 3, 3, 5, 4, 3])

In [38]:
l.flatten().ndim

1

In [39]:
l.shape

(3, 3)

In [40]:
np.random.randn(5, 5)

array([[-0.79360208,  1.26421765,  0.96170461,  1.43991291, -0.48703691],
       [ 1.36197618,  0.88795646,  0.42534392,  0.36449305,  2.31766479],
       [-0.81435057, -1.36506074, -0.21390126,  1.38288694,  1.25075309],
       [ 0.70922505, -1.52443798,  0.10586289, -0.0269509 , -1.06259619],
       [-0.67553864, -0.1545027 , -0.74882338,  2.45474587,  0.26455294]])

In [41]:
np.cos(40)

-0.6669380616522619

In [42]:
np.cos??

In [43]:
np.linspace(-3, 3, 1000)

array([-3.        , -2.99399399, -2.98798799, -2.98198198, -2.97597598,
       -2.96996997, -2.96396396, -2.95795796, -2.95195195, -2.94594595,
       -2.93993994, -2.93393393, -2.92792793, -2.92192192, -2.91591592,
       -2.90990991, -2.9039039 , -2.8978979 , -2.89189189, -2.88588589,
       -2.87987988, -2.87387387, -2.86786787, -2.86186186, -2.85585586,
       -2.84984985, -2.84384384, -2.83783784, -2.83183183, -2.82582583,
       -2.81981982, -2.81381381, -2.80780781, -2.8018018 , -2.7957958 ,
       -2.78978979, -2.78378378, -2.77777778, -2.77177177, -2.76576577,
       -2.75975976, -2.75375375, -2.74774775, -2.74174174, -2.73573574,
       -2.72972973, -2.72372372, -2.71771772, -2.71171171, -2.70570571,
       -2.6996997 , -2.69369369, -2.68768769, -2.68168168, -2.67567568,
       -2.66966967, -2.66366366, -2.65765766, -2.65165165, -2.64564565,
       -2.63963964, -2.63363363, -2.62762763, -2.62162162, -2.61561562,
       -2.60960961, -2.6036036 , -2.5975976 , -2.59159159, -2.58

In [44]:
import pandas as pd

In [45]:
a = {
    'key1': list('abcdef'),
    'key2': list(range(6)),
    'key3': list('ABCDEF')
}

In [46]:
df = pd.DataFrame(a)

In [47]:
a

{'key1': ['a', 'b', 'c', 'd', 'e', 'f'],
 'key2': [0, 1, 2, 3, 4, 5],
 'key3': ['A', 'B', 'C', 'D', 'E', 'F']}

In [48]:
df

key1  key2 key3
0    a     0    A
1    b     1    B
2    c     2    C
3    d     3    D
4    e     4    E
5    f     5    F

In [49]:
a['key1']

['a', 'b', 'c', 'd', 'e', 'f']

In [50]:
df['key1']

0    a
1    b
2    c
3    d
4    e
5    f
Name: key1, dtype: object

In [51]:
df['key2']

0    0
1    1
2    2
3    3
4    4
5    5
Name: key2, dtype: int64

In [52]:
arr = np.random.randn(100, 100)

In [53]:
np.eye(10, 10)       ####

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [54]:
arr

array([[-0.13273697,  1.50666784,  0.06228793, ...,  0.05581466,
        -0.59967885, -0.19505675],
       [-0.40059536, -0.76438472, -1.79906513, ..., -1.36097081,
        -0.41573632,  1.66062389],
       [-0.60390832,  0.25786141, -0.32178998, ..., -0.27537098,
        -0.14809542, -1.15044013],
       ...,
       [-0.56692078, -0.75361681, -0.74761441, ..., -0.42755012,
         0.5150396 , -1.32505221],
       [-1.18844811,  0.83614949,  0.06382168, ...,  0.18014739,
        -1.87167357,  0.53495042],
       [-1.92337568, -0.10236752,  0.31985035, ...,  0.24977392,
         0.03629401,  0.57940057]])

In [55]:
arr.shape

(100, 100)

In [56]:
arr.ndim

2

In [57]:
df = pd.DataFrame(arr)

In [58]:
df

0         1         2         3         4         5         6   \
0  -0.132737  1.506668  0.062288  1.793536 -2.203373  0.788893 -0.023400   
1  -0.400595 -0.764385 -1.799065  1.006546 -0.580376  0.939310  0.798495   
2  -0.603908  0.257861 -0.321790  2.629573  0.962257  0.089496 -1.298521   
3   0.020379  0.700120  0.339405 -0.961729 -0.901283 -0.042759 -0.394523   
4  -0.312363 -0.166543 -0.755624 -0.263839 -1.425369  0.831368 -2.558132   
5  -0.552386  0.425584 -0.512506  1.974953 -0.434147 -0.846458 -1.132649   
6  -0.147845  0.261183 -1.249570  2.224147 -0.396627  0.636996 -0.738230   
7   0.314589  0.346848 -0.063141  1.457735  0.240754  0.756275 -0.725774   
8   0.212625  0.079098  0.171259  0.747746 -1.295656  0.572353  0.880904   
9   0.399039  0.265793  1.220753  1.604146 -0.647009 -0.779114  0.841326   
10 -0.487433  0.775002  0.720448 -1.430810  1.579769  0.138704 -0.052910   
11  0.080419 -0.217770  0.479283 -0.003576  0.027221  0.056267 -0.231770   
12  0.932506 -0.418320 -1.073788 -0.845622 -0.257308 -0.045006 -0.901776   
13 -0.023797 -0.820307  1.562872 -0.424897  0.683778 -0.413474  1.147861   
14 -1.195909 -0.266460  0.886770  0.663646 -0.666360 -0.400709  1.229311   
15  0.197357  0.596468  1.106456 -0.066703 -0.915192  0.008656 -1.095319   
16 -0.061337  0.298664  0.947066  0.656968  0.483920 -1.179605  0.104386   
17 -0.453240 -0.035885  0.317166  2.392074  0.426407 -0.992425 -0.029492   
18  1.088352  1.935152 -0.305405 -0.041941 -0.977352  0.546527 -2.413466   
19  1.197444 -0.033544 -1.126361  1.076170  0.627965  0.713935  0.490039   
20  0.516170 -0.438678 -0.968186  0.224148 -0.925753  1.093006 -0.783787   
21  0.399624  0.243624 -1.008943  1.153172  0.270696  0.133021  1.159127   
22 -0.288921 -0.585912  0.324845  0.504795  1.561756  0.558856  1.378650   
23 -0.649134 -0.051626 -0.599914 -0.764310 -0.901728  0.944276 -0.966804   
24  0.531882 -0.826329  1.408129  0.382729  0.872445 -0.942618 -0.648340   
25  0.993284 -0.044875  0.123677  1.072309 -1.272864  2.029928  1.585890   
26  0.472856 -1.000257 -1.589881  0.017893 -2.274063 -0.405451 -1.288293   
27  0.897397  0.292459  0.461665 -0.262510  0.556896 -0.618909 -0.301103   
28  1.107412  0.308049 -0.553747 -0.318136  0.695728  0.605504 -0.420571   
29 -0.039622 -0.224115 -0.095145 -1.127701  1.173923 -1.734807 -0.478278   
..       ...       ...       ...       ...       ...       ...       ...   
70  1.038088  0.034171 -1.179803  0.593929 -0.028435  0.520194 -0.569388   
71 -0.246006 -0.202185 -2.432778 -0.426599  0.983699  0.980334 -0.231969   
72  0.591825  0.650129 -1.261932  0.821684  1.396417 -0.311660 -0.421201   
73 -0.732543 -1.344602 -1.414303  0.275790  0.177838 -0.440781  0.625039   
74  0.566524 -0.777401 -0.199315  1.479548  0.359471  1.519246 -0.408900   
75  0.401706  0.565065 -1.503325 -2.455791  1.284920 -0.815479  0.660135   
76  0.090276  0.103639 -0.320739  0.139645 -0.347368 -0.068489 -0.148287   
77  1.781082  0.990864 -0.932179  0.539254 -0.938127  0.138412  0.175385   
78  1.010160 -2.146487  0.050608  1.458820 -0.007396  0.663032 -0.035896   
79  1.384225 -0.268728  0.716538  0.498074 -1.412860  1.031059  0.183745   
80 -2.058809 -0.269114 -0.319694  1.283498 -1.121879 -0.051541 -0.214653   
81  0.941346 -1.078740 -0.387701 -1.458821 -0.604883 -2.921751 -0.552725   
82 -0.876480 -1.284437  1.250571 -1.715479 -1.077150 -0.771422 -2.134418   
83 -2.343855 -0.749699  0.153057 -0.454317 -0.390836  0.193689 -0.218136   
84 -0.138581 -0.547916  0.643245 -0.937902  0.613016  0.891529  2.455071   
85  1.625370 -0.581226 -0.346687  1.147366  1.530594  0.203243 -1.275490   
86 -0.057027  0.855791  1.304825  0.989734  0.325911  0.797395 -0.179957   
87 -0.355690 -1.050190 -0.231371 -2.183221 -1.251338  1.644570  1.435015   
88 -2.592834  0.387233  1.311627  1.545581 -0.210794  0.568414  1.196146   
89 -1.991098  0.677755 -1.663510  0.446109  0.014942 -0.817592  0.158815   
90 -1.034576  0.536927  0.758824  0.355716  0.225628  1.22

In [59]:
df[:5]

0         1         2         3         4         5         6   \
0 -0.132737  1.506668  0.062288  1.793536 -2.203373  0.788893 -0.023400   
1 -0.400595 -0.764385 -1.799065  1.006546 -0.580376  0.939310  0.798495   
2 -0.603908  0.257861 -0.321790  2.629573  0.962257  0.089496 -1.298521   
3  0.020379  0.700120  0.339405 -0.961729 -0.901283 -0.042759 -0.394523   
4 -0.312363 -0.166543 -0.755624 -0.263839 -1.425369  0.831368 -2.558132   

         7         8         9     ...           90        91        92  \
0  0.134764  1.064327  0.398139    ...    -0.914685 -0.744730 -1.741326   
1  0.088929 -0.898661 -0.689698    ...    -0.242173  0.276469  0.953536   
2 -0.556105 -0.551301  0.916028    ...     0.502117 -1.955570 -2.095615   
3  0.914951  0.191691  0.426438    ...     0.723399  1.344237  0.083795   
4  1.003905  1.245345 -0.890883    ...     1.388285 -0.518046 -0.984338   

         93        94        95        96        97        98        99  
0  0.758048  0.962467  1.119322 -0.270592  0.055815 -0.599679 -0.195057  
1  0.492349 -0.087113  0.881942  0.319853 -1.360971 -0.415736  1.660624  
2  1.308249  0.345920  0.060172 -0.902098 -0.275371 -0.148095 -1.150440  
3  1.142375 -0.837185  0.164546 -0.913500  1.029377 -1.065825 -1.080834  
4  0.014184  1.383817 -0.352221 -1.526547  0.753740  0.499332 -0.180373  

[5 rows x 100 columns]

In [60]:
df[-5:]

0         1         2         3         4         5         6   \
95  0.913339 -0.958526  1.136599 -0.127303 -0.201437  0.142379 -1.018075   
96 -0.140254  1.094328  0.072467 -0.326742  0.277383 -1.393651 -1.092270   
97 -0.566921 -0.753617 -0.747614  0.799992  1.075979 -0.213870  0.590024   
98 -1.188448  0.836149  0.063822  0.560714 -0.680854 -0.891230  0.502840   
99 -1.923376 -0.102368  0.319850  0.433694 -0.064457  0.622995  0.433570   

          7         8         9     ...           90        91        92  \
95  3.032442 -0.846705  0.907273    ...     0.412302  0.576877  1.435203   
96 -0.288228  0.185538  0.601847    ...    -0.702849 -0.396385 -0.647465   
97  2.205233  0.786802 -0.912849    ...     1.410009 -2.551456 -0.638223   
98 -1.495819  0.431732  1.913110    ...     0.342334  0.825187  0.842780   
99 -1.352073  0.655056  0.102644    ...    -0.156713  0.250649 -0.294043   

          93        94        95        96        97        98        99  
95 -0.699939 -1.092124 -1.732834 -0.533661  0.248389  0.889189 -0.099426  
96  0.028119  1.435656  1.174824 -0.066850  0.197099 -0.871671 -1.190223  
97 -0.363123 -1.245351 -0.340961 -2.007803 -0.427550  0.515040 -1.325052  
98 -0.280971 -0.366745  1.481851 -0.092170  0.180147 -1.871674  0.534950  
99  0.672985  2.090010  1.092214 -0.432507  0.249774  0.036294  0.579401  

[5 rows x 100 columns]

In [61]:
df.head()

0         1         2         3         4         5         6   \
0 -0.132737  1.506668  0.062288  1.793536 -2.203373  0.788893 -0.023400   
1 -0.400595 -0.764385 -1.799065  1.006546 -0.580376  0.939310  0.798495   
2 -0.603908  0.257861 -0.321790  2.629573  0.962257  0.089496 -1.298521   
3  0.020379  0.700120  0.339405 -0.961729 -0.901283 -0.042759 -0.394523   
4 -0.312363 -0.166543 -0.755624 -0.263839 -1.425369  0.831368 -2.558132   

         7         8         9     ...           90        91        92  \
0  0.134764  1.064327  0.398139    ...    -0.914685 -0.744730 -1.741326   
1  0.088929 -0.898661 -0.689698    ...    -0.242173  0.276469  0.953536   
2 -0.556105 -0.551301  0.916028    ...     0.502117 -1.955570 -2.095615   
3  0.914951  0.191691  0.426438    ...     0.723399  1.344237  0.083795   
4  1.003905  1.245345 -0.890883    ...     1.388285 -0.518046 -0.984338   

         93        94        95        96        97        98        99  
0  0.758048  0.962467  1.119322 -0.270592  0.055815 -0.599679 -0.195057  
1  0.492349 -0.087113  0.881942  0.319853 -1.360971 -0.415736  1.660624  
2  1.308249  0.345920  0.060172 -0.902098 -0.275371 -0.148095 -1.150440  
3  1.142375 -0.837185  0.164546 -0.913500  1.029377 -1.065825 -1.080834  
4  0.014184  1.383817 -0.352221 -1.526547  0.753740  0.499332 -0.180373  

[5 rows x 100 columns]

In [62]:
df.head(10)

0         1         2         3         4         5         6   \
0 -0.132737  1.506668  0.062288  1.793536 -2.203373  0.788893 -0.023400   
1 -0.400595 -0.764385 -1.799065  1.006546 -0.580376  0.939310  0.798495   
2 -0.603908  0.257861 -0.321790  2.629573  0.962257  0.089496 -1.298521   
3  0.020379  0.700120  0.339405 -0.961729 -0.901283 -0.042759 -0.394523   
4 -0.312363 -0.166543 -0.755624 -0.263839 -1.425369  0.831368 -2.558132   
5 -0.552386  0.425584 -0.512506  1.974953 -0.434147 -0.846458 -1.132649   
6 -0.147845  0.261183 -1.249570  2.224147 -0.396627  0.636996 -0.738230   
7  0.314589  0.346848 -0.063141  1.457735  0.240754  0.756275 -0.725774   
8  0.212625  0.079098  0.171259  0.747746 -1.295656  0.572353  0.880904   
9  0.399039  0.265793  1.220753  1.604146 -0.647009 -0.779114  0.841326   

         7         8         9     ...           90        91        92  \
0  0.134764  1.064327  0.398139    ...    -0.914685 -0.744730 -1.741326   
1  0.088929 -0.898661 -0.689698    ...    -0.242173  0.276469  0.953536   
2 -0.556105 -0.551301  0.916028    ...     0.502117 -1.955570 -2.095615   
3  0.914951  0.191691  0.426438    ...     0.723399  1.344237  0.083795   
4  1.003905  1.245345 -0.890883    ...     1.388285 -0.518046 -0.984338   
5 -1.582742 -0.085109 -0.722246    ...     0.110253 -0.020237  1.690627   
6  0.908237 -2.888955 -0.067663    ...    -1.186614 -0.666999  0.190401   
7 -0.058733 -1.166850 -0.383913    ...     0.700918 -1.890481  0.608958   
8 -0.622727 -0.876861 -0.376659    ...    -0.997612 -0.157481 -1.355531   
9  0.163804 -0.631090 -1.230998    ...     1.037428 -0.272731  1.961071   

         93        94        95        96        97        98        99  
0  0.758048  0.962467  1.119322 -0.270592  0.055815 -0.599679 -0.195057  
1  0.492349 -0.087113  0.881942  0.319853 -1.360971 -0.415736  1.660624  
2  1.308249  0.345920  0.060172 -0.902098 -0.275371 -0.148095 -1.150440  
3  1.142375 -0.837185  0.164546 -0.913500  1.029377 -1.065825 -1.080834  
4  0.014184  1.383817 -0.352221 -1.526547  0.753740  0.499332 -0.180373  
5  0.684393  0.349617 -1.476262  0.582525 -0.909970  1.498787  1.402566  
6  1.685440  0.059652  0.666576 -0.819383 -0.663444 -0.414121  0.016118  
7 -2.641917  0.156806 -0.456920 -1.881123 -0.145644  1.437017  0.108516  
8 -0.236279 -0.976026  0.875144 -1.462184  0.390390 -0.640707 -0.663874  
9  0.801260  0.322400 -0.657936  0.800732  2.705579 -0.225727  0.359907  

[10 rows x 100 columns]

In [63]:
df.tail(10)

0         1         2         3         4         5         6   \
90 -1.034576  0.536927  0.758824  0.355716  0.225628  1.220838  0.580854   
91 -1.199743  1.756357 -0.661818 -0.266950  0.209104  1.360385  0.241582   
92  0.698771  0.300402 -0.697864  1.458138 -0.777373 -0.655475 -0.344190   
93  0.606615  0.841083 -1.830785  0.429676 -0.709054 -0.627247 -0.575073   
94  0.393779  1.926418 -1.143287 -0.685426 -0.830184 -0.344050 -0.596812   
95  0.913339 -0.958526  1.136599 -0.127303 -0.201437  0.142379 -1.018075   
96 -0.140254  1.094328  0.072467 -0.326742  0.277383 -1.393651 -1.092270   
97 -0.566921 -0.753617 -0.747614  0.799992  1.075979 -0.213870  0.590024   
98 -1.188448  0.836149  0.063822  0.560714 -0.680854 -0.891230  0.502840   
99 -1.923376 -0.102368  0.319850  0.433694 -0.064457  0.622995  0.433570   

          7         8         9     ...           90        91        92  \
90  0.494770  0.821354 -0.561651    ...    -1.710311  0.547133 -0.547633   
91 -1.099991  0.094463 -0.567391    ...    -0.371037  0.561079 -0.841563   
92  0.250445 -0.048097  0.047522    ...     1.255458 -1.157888 -0.131553   
93  0.440921  0.894902 -0.005475    ...    -0.019451  0.553675 -0.456423   
94 -0.639877 -0.560986  1.716858    ...    -1.033582  0.015471  1.608634   
95  3.032442 -0.846705  0.907273    ...     0.412302  0.576877  1.435203   
96 -0.288228  0.185538  0.601847    ...    -0.702849 -0.396385 -0.647465   
97  2.205233  0.786802 -0.912849    ...     1.410009 -2.551456 -0.638223   
98 -1.495819  0.431732  1.913110    ...     0.342334  0.825187  0.842780   
99 -1.352073  0.655056  0.102644    ...    -0.156713  0.250649 -0.294043   

          93        94        95        96        97        98        99  
90  0.096994 -0.947904  0.970492  0.264255  1.786133 -0.942077  1.469884  
91 -0.049230  0.010694 -0.514155  0.802892 -1.974514 -0.574014  0.349599  
92 -0.804927 -1.041660  0.288219  0.553040  0.069305  1.838572  0.509321  
93 -0.278502 -0.457892 -0.348286  0.162388  0.159480  1.102935  0.588072  
94  1.523985  0.917438 -0.235549 -1.161944  0.401426  0.405794  0.336035  
95 -0.699939 -1.092124 -1.732834 -0.533661  0.248389  0.889189 -0.099426  
96  0.028119  1.435656  1.174824 -0.066850  0.197099 -0.871671 -1.190223  
97 -0.363123 -1.245351 -0.340961 -2.007803 -0.427550  0.515040 -1.325052  
98 -0.280971 -0.366745  1.481851 -0.092170  0.180147 -1.871674  0.534950  
99  0.672985  2.090010  1.092214 -0.432507  0.249774  0.036294  0.579401  

[10 rows x 100 columns]

In [64]:
## .loc --> index
## .iloc --> Columns


df.iloc[0:2, 3:6]

3         4         5
0  1.793536 -2.203373  0.788893
1  1.006546 -0.580376  0.939310

In [65]:
df.loc[0:2, 3:6]

3         4         5         6
0  1.793536 -2.203373  0.788893 -0.023400
1  1.006546 -0.580376  0.939310  0.798495
2  2.629573  0.962257  0.089496 -1.298521

In [66]:
a

{'key1': ['a', 'b', 'c', 'd', 'e', 'f'],
 'key2': [0, 1, 2, 3, 4, 5],
 'key3': ['A', 'B', 'C', 'D', 'E', 'F']}

In [67]:
df = pd.DataFrame(a)

In [68]:
df

key1  key2 key3
0    a     0    A
1    b     1    B
2    c     2    C
3    d     3    D
4    e     4    E
5    f     5    F

In [69]:
df.iloc[0:3, 0:2]

key1  key2
0    a     0
1    b     1
2    c     2

In [70]:
df.loc[0:2, ['key3', 'key2']]

key3  key2
0    A     0
1    B     1
2    C     2

In [71]:
df

key1  key2 key3
0    a     0    A
1    b     1    B
2    c     2    C
3    d     3    D
4    e     4    E
5    f     5    F

In [72]:
df.to_csv('df_from_sc.csv')



## reading , loading, and analysis

In [ ]:
!housing